Nugget.config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear/>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="eviCoreVSTSNugetFeed" value="https://pkgs.dev.azure.com/eviCoreDev/_packaging/eviCoreVSTSNugetFeed/nuget/v3/index.json" />
  </packageSources>
</configuration>


pr-pipeline.yml
trigger: none # Disable CI triggers.

name: 'ucx-evicore-event-source-pr'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: ucxAdoTemplates
      type: git
      name: 'UCX/ucx-ado-templates'

stages:
  - stage:
    jobs:
      - template: dotnet/pull-request.yaml@ucxAdoTemplates
        parameters:
          dotnetVersion: '7.x'
          nugetConfigPath: './NuGet.Config'
          solutionPath: './ucx.messages.sln'
          testPath: './ucx.messages.sln'
          SonarQubeProjectKey: 'ucx.messages'
          SonarQubeProjectName: 'ucx.messages'
          RunSonarQubeAnalysis: true
          CheckmarxProjectName: 'ucx.messages'
          CheckmarxServiceConnection: 'UCX-Checkmarx-SAST-Service-Connection'
          CheckmarxFullTeamName: 'CxServer/Cigna/UCX'
          CheckmarxProjectRepoUrl: 'https://eviCoreDev@dev.azure.com/eviCoreDev/UCX/_git/ucx.messages'
          CheckmarxPointOfContactEmail: 'elizabeth.langkau@evicore.com'
          RunCheckMarxAnalysis: true

RELEASE PIPELINE
trigger:
  branches:
    include:
      - main
pool:
  name: ubuntu-latest
resources:
  repositories:
    - repository: ucxAdoTemplates
      type: git
      name: 'UCX/ucx-ado-templates'
variables:
  buildConfiguration: 'Release'
  projectPath: 'ucx.messages/ucx.messages.csproj'
  solutionPath: 'ucx.messages.sln'
  unitTestProjectPath: 'ucx.messages.sln'
  publishFeed: 'eb6a6b78-0104-45b0-b0e6-03d649a3a686/51c8c92d-0a26-44b7-b6e5-c6f6b8f472e7'
  dotnetVersion: '7.x'
  nugetConfigPath: 'NuGet.Config'

stages:
  - stage: BuildAndTest
    jobs:
      - template: dotnet/build-and-test.yaml@ucxAdoTemplates
        parameters:
          dotnetVersion: $(dotnetVersion)
          nugetConfigPath: $(nugetConfigPath)
          solutionPath: $(solutionPath)
          testPath: $(unitTestProjectPath)
  - stage: EditorConfigCheck
    dependsOn: BuildAndTest
    jobs:
      - job:
        steps:
          - template: misc/editor-config-template.yml@ucxAdoTemplates
            parameters:
              pathToCheck: '$(git ls-files)'
  - stage: DeployPackage
    jobs:
      - template: dotnet/nuget-pack-and-deploy.yaml@ucxAdoTemplates
        parameters:
          buildConfiguration: $(buildConfiguration)
          projectPath: $(projectPath)
          publishFeed: $(publishFeed)
          solutionPath: $(solutionPath)
          nugetConfigPath: $(nugetConfigPath)
          dotnetVersion: $(dotnetVersion)



Thanks and Regards
Siraj

From: R, Sirajudeen (CTR) <Sirajudeen.R@evicore.com> 
Sent: Tuesday, August 20, 2024 8:29 PM
To: R, Sirajudeen (CTR) <Sirajudeen.R@evicore.com>
Subject: ngtpipeline



Thanks and Regards
Siraj

